version: 2
updates:
  - package-ecosystem: nuget
    directory: "/App"
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: "/Client"
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: "/Core"
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: "/Demo"
    schedule:
      interval: weekly

  - package-ecosystem: nuget
    directory: "/Service"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
