import "oaidl.idl";
import "ocidl.idl";

[
    uuid(dc51fb4b-bd5d-4613-8786-e154926b7035),
    version(2.0),
    helpstring("FireBox Type Library")
]
library FireBoxLib
{
    importlib("stdole2.tlb");

    typedef [uuid(d1a2b3c4-e5f6-4a7b-8c9d-0e1f2a3b4c5d), public]
    struct UsageStruct {
        hyper promptTokens;
        hyper completionTokens;
        hyper totalTokens;
    } UsageStruct;

    typedef [uuid(d7a8b9c0-e1f2-4a3b-4c5d-6e7f8091a2b3), public]
    struct ChatCompletionResultStruct {
        VARIANT_BOOL hasResponse;
        BSTR modelId;
        BSTR messageRole;
        BSTR messageContent;
        BSTR reasoningText;
        hyper usagePromptTokens;
        hyper usageCompletionTokens;
        hyper usageTotalTokens;
        BSTR finishReason;
        BSTR errorMessage;
    } ChatCompletionResultStruct;

    typedef [uuid(f9c0d1e2-a3b4-4c5d-6e7f-8091a2b3c4d5), public]
    struct EmbeddingResultStruct {
        VARIANT_BOOL hasResponse;
        BSTR modelId;
        hyper indicesArray;
        hyper flatVectorsArray;
        int embeddingCount;
        int vectorDimension;
        hyper usagePromptTokens;
        hyper usageCompletionTokens;
        hyper usageTotalTokens;
        BSTR errorMessage;
    } EmbeddingResultStruct;

    typedef [uuid(a0d1e2f3-b4c5-4d6e-7f80-91a2b3c4d5e6), public]
    struct FunctionCallResultStruct {
        VARIANT_BOOL hasResponse;
        BSTR modelId;
        BSTR outputJson;
        hyper usagePromptTokens;
        hyper usageCompletionTokens;
        hyper usageTotalTokens;
        BSTR finishReason;
        BSTR errorMessage;
    } FunctionCallResultStruct;

    [
        object,
        uuid(e0df9d43-d19e-4125-9c9e-277020a62cb4),
        oleautomation,
        pointer_default(unique)
    ]
    interface IFireBoxControl : IUnknown
    {
        [id(1)] HRESULT Ping([in] BSTR message, [out, retval] BSTR* result);
        [id(2)] HRESULT Shutdown();
        [id(3)] HRESULT GetVersionCode([out, retval] int* versionCode);

        [id(4)] HRESULT GetDailyStats([in] int year, [in] int month, [in] int day, [out, retval] BSTR* result);
        [id(5)] HRESULT GetMonthlyStats([in] int year, [in] int month, [out, retval] BSTR* result);

        [id(6)] HRESULT ListProviders([out, retval] BSTR* result);
        [id(7)] HRESULT AddProvider([in] BSTR providerType, [in] BSTR name, [in] BSTR baseUrl, [in] BSTR apiKey, [out, retval] int* providerId);
        [id(8)] HRESULT UpdateProvider([in] int providerId, [in] BSTR name, [in] BSTR baseUrl, [in] BSTR apiKey, [in] int apiKeyProvided, [in] BSTR enabledModelIdsJson);
        [id(9)] HRESULT DeleteProvider([in] int providerId);
        [id(10)] HRESULT FetchProviderModels([in] int providerId, [out, retval] BSTR* result);

        [id(11)] HRESULT ListRoutes([out, retval] BSTR* result);
        [id(12)] HRESULT AddRoute([in] BSTR routeId, [in] BSTR strategy, [in] BSTR candidatesJson, [in] int reasoning, [in] int toolCalling, [in] int inputFormatsMask, [in] int outputFormatsMask, [out, retval] int* routeNumericId);
        [id(13)] HRESULT UpdateRoute([in] int routeNumericId, [in] BSTR routeId, [in] BSTR strategy, [in] BSTR candidatesJson, [in] int reasoning, [in] int toolCalling, [in] int inputFormatsMask, [in] int outputFormatsMask);
        [id(14)] HRESULT DeleteRoute([in] int routeNumericId);

        [id(15)] HRESULT ListConnections([out, retval] BSTR* result);

        [id(16)] HRESULT ListClientAccess([out, retval] BSTR* result);
        [id(17)] HRESULT UpdateClientAccessAllowed([in] int accessId, [in] int isAllowed);
    };

    [
        object,
        uuid(a3c7f1d2-8b4e-4f6a-9d1c-5e2b8a0f3c7d),
        oleautomation,
        pointer_default(unique)
    ]
    interface IFireBoxStreamCallback : IUnknown
    {
        [id(1)] HRESULT OnStarted([in] hyper requestId);
        [id(2)] HRESULT OnDelta([in] hyper requestId, [in] BSTR deltaText);
        [id(3)] HRESULT OnReasoningDelta([in] hyper requestId, [in] BSTR reasoningText);
        [id(4)] HRESULT OnUsage([in] hyper requestId, [in] hyper promptTokens, [in] hyper completionTokens, [in] hyper totalTokens);
        [id(5)] HRESULT OnCompleted([in] hyper requestId, [in] BSTR modelId, [in] BSTR messageRole, [in] BSTR messageContent, [in] BSTR reasoningText, [in] BSTR finishReason, [in] hyper usagePromptTokens, [in] hyper usageCompletionTokens, [in] hyper usageTotalTokens);
        [id(6)] HRESULT OnError([in] hyper requestId, [in] BSTR error);
        [id(7)] HRESULT OnCancelled([in] hyper requestId);
    };

    [
        object,
        uuid(9d611e53-2f5a-4987-870f-e58f58e4a7f2),
        oleautomation,
        pointer_default(unique)
    ]
    interface IFireBoxCapability : IUnknown
    {
        [id(1)] HRESULT Ping([in] BSTR message, [out, retval] BSTR* result);
        [id(2)] HRESULT ListModels([out, retval] BSTR* result);
        [id(3)] HRESULT ChatCompletion([in] BSTR modelId, [in] BSTR messagesJson, [in] float temperature, [in] int maxOutputTokens, [in] int reasoningEffort, [out, retval] ChatCompletionResultStruct* result);
        [id(4)] HRESULT StartChatCompletionStream([in] BSTR modelId, [in] BSTR messagesJson, [in] float temperature, [in] int maxOutputTokens, [in] int reasoningEffort, [in] IFireBoxStreamCallback* callback, [out, retval] hyper* requestId);
        [id(5)] HRESULT CancelChatCompletion([in] hyper requestId);
        [id(6)] HRESULT CreateEmbeddings([in] BSTR modelId, [in] hyper inputArray, [out, retval] EmbeddingResultStruct* result);
        [id(7)] HRESULT CallFunction([in] BSTR modelId, [in] BSTR functionName, [in] BSTR functionDescription, [in] BSTR inputJson, [in] BSTR inputSchemaJson, [in] BSTR outputSchemaJson, [in] float temperature, [in] int maxOutputTokens, [out, retval] FunctionCallResultStruct* result);
    };

    [uuid(bce2f493-0f9b-473b-8df5-727bbf82cf7f)]
    coclass FireBoxControlClass
    {
        [default] interface IFireBoxControl;
    };

    [uuid(b2a4e3a1-7254-4876-aca8-81f46b4f78a1)]
    coclass FireBoxCapabilityClass
    {
        [default] interface IFireBoxCapability;
    };
};
